[tool.robo]
name = "Simple Automation"
description = "Very simple automation "
python = "3.9.13"

[tool.robo.dependencies]
robo-core="robo-0.1.1-py3-none-any.whl"

[tool.robo.dev-dependencies]
ruff="0.0.1"
black="0.0.1"
