[tool.robo]
name = "RPA Challenge"
description = "A simple example robot that solves the RPA Challenge"
python = "3.9.13"

[tool.robo.dependencies]
robocorp-core="0.1.3"
robocorp-browser="0.1.0"
robocorp-excel="0.1.0"
robocorp-http="0.1.0"

[tool.robo.dev-dependencies]
ruff="0.0.260"
black="23.3.0"
