[tool.robo]
name = "RPA Challenge"
description = "A simple example robot that solves the RPA Challenge"
python = "3.9.13"

[tool.robo.dependencies]
robo-core="robo-0.1.2-py3-none-any.whl"
robo-libs="robo_libs-0.1.0-py3-none-any.whl"

[tool.robo.dev-dependencies]
ruff="0.0.260"
black="23.3.0"

[tool.ruff]
# TODO: We should generate this inside the hood
target-version = "py39"
